tasks:
  - init: |
      docker-compose build --pull webdav
    command: |
      docker-compose up -d webdav
  - init: |
      npm install
    command: |
      npm run watch

ports:
  - port: 8080
    onOpen: open-preview
